CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true

GPUS: (0,)
OUTPUT_DIR: 'output_train_w48'
LOG_DIR: 'log'
WORKERS: 1
PRINT_FREQ: 10

MASK:
  USE: true
  INTERPOLATION: rbf
  P: 0.5
  CONF_THRE: 0.998
  ENTROPY_THRE: 0.0
  CRIT: conf_thre
  AGGR: copy

EXIT:
  TYPE: flex #original
  FINAL_CONV_KERNEL: 1
  INTER_CHANNEL: 128

DATASET:
  DATASET: gta5
  ROOT: 'RC-EENN/sem_seg/data/'
  TEST_SET: 'list/gta5/allval.lst'
  TRAIN_SET: 'list/gta5/train.lst'
  NUM_CLASSES: 19

MODEL:
  NAME: 'model_anytime'
  PRETRAINED: 'pretrained_models/hrnetv2_w48_imagenet_pretrained.pth'
  LOAD_STAGE: 0
  EXTRA:
    EE_WEIGHTS: (1,1,1,1)
    AGGREGATION: none
    EARLY_DETACH: false
    EXIT_NORM: BN
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM

LOSS:
  USE_OHEM: false
  OHEMTHRES: 0.9
  OHEMKEEP: 131072

TRAIN:
  EE_ONLY: false
  ALLE_ONLY: false
  IMAGE_SIZE:
  - 1024
  - 512
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 3 # 484
  RESUME: false
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 16

TEST:
  SUB_DIR: ''
  IMAGE_SIZE:
  - 2048
  - 1024
  BASE_SIZE: 2048
  BATCH_SIZE_PER_GPU: 4
  CENTER_CROP_TEST: false
  MODEL_FILE: 'pretrained_models/final_state.pth'